
name: Code Coverage Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y gfortran gcc

    - name: Verify compiler and tools
      run: |
        gfortran --version
        gcov --version

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Hatch
      run: pipx install hatch

    - name: Build and install with coverage instrumentation
      run: |
        make coverage-build && make coverage-install

    - name: Run tests to generate coverage data
      run: |
        export PATH="$PWD/bin:$PATH"
        hatch run test

    - name: Generate coverage reports
      run: |
        make coverage-report
        
    - name: Generate HTML coverage reports for FORD integration
      run: |
        make coverage-html
        
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: |
          **/*.gcov
          docs/*.html
        retention-days: 3
